<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="Skin/Css/style.css">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <script src="Skin/js/jquery-3.6.4.min.js"></script>
    <script  src="http://localhost/newmvc-parthj/skin/js/AJAX.js"></script>

    <?php foreach($this->getAllJs() as $src):?>
    <script  src="<?php echo $src; ?>"></script>
    <?php endforeach;?>

    <title><?php echo $this->getTitle();?></title>
</head>