<?php
$shippingMethod = $this->getShippingMethod();
$action = $shippingMethod->method_id ? 'Edit' : 'Add';
?>

<div class="container">
    <form action="<?php echo $this->getUrl("save",null,["id"=>$shippingMethod->method_id],true);?>" method="post" id="shipping-form">
        <div class="row">
            <div class="col-6">
                <h1 class="my-5 mb-4 fs-2">
                    <?php echo $action ?> Shipping Method
                </h1>

                <div class="mb-2 row">
                    <label for="shippingMethod-name" class="col-sm-3 col-form-label">Name:</label>
                    <div class="col-sm-5">
                        <input type="text" class="form-control" name="shippingMethod[name]"
                            value="<?php echo $shippingMethod->name ?>" id="shippingMethod-name"
                            placeholder="Enter the name...">
                    </div>
                </div>

                <div class="mb-2 row">
                    <label for="shippingMethod-amount" class="col-sm-3 col-form-label">Amount:</label>
                    <div class="col-sm-5">
                        <input type="number" name="shippingMethod[amount]" class="form-control"
                            value="<?php echo $shippingMethod->amount ?>" id="shippingMethod-amount"
                            placeholder="amount...">
                    </div>
                </div>


                <div class="mb-2 row">
                    <label for="shippingMethod-status" class="col-sm-3 col-form-label">Status:</label>
                    <div class="col-sm-3">
                        <select class="form-select" name="shippingMethod[status]" id="shippingMethod-status">
                            <?php foreach ($shippingMethod->getResource()->getStatusOptions() as $key => $value): ?>
                                <?php $selected = ($key == $shippingMethod->getStatus()) ? 'selected' : ''; ?>
                                <option value="<?php echo $key ?>" <?php echo $selected; ?>>
                                    <?php echo $value ?>
                                </option>
                            <?php endforeach; ?>
                        </select>
                    </div>
                </div>

            </div>

        </div>
        <div class="d-flex mt-5">
            <button type="button" onclick="ajax.setUrl('<?php echo $this->getUrl('grid'); ?>').call()" class="btn btn-danger me-2">Cancel</button>
            <button class="btn btn-primary" type="button" onclick="ajax.setForm('shipping-form').call()">Create</button>
        </div>
    </form>
</div>