<?php 
$row = $this->getRow();
$attribute = $this->getAttribute();?>
<?php $options = $attribute->getOptions();?>
<?php $value = $row->getAttributeValue($attribute); ?>

<?php if($options):?>
<div class="col-sm-auto">
    <select class="form-select cursor-pointer" name="attribute[<?php echo $attribute->backend_type?>][<?php echo $attribute->getId()?>]">
        <option value="0" hidden selected>Select</option>
        <?php foreach($options->getData() as $option): ?>
        <option value="<?php echo $option->getId()?>" <?php if($option->getId()==$value){echo "selected";} ?>><?php echo $option->name?></option>
        <?php endforeach; ?>
    </select>
</div>
<?php endif;?>