<?php 
$collection = $this->getCollection();
$currentSalesman = $collection['salesman'];
$rows = $collection['salesman_prices'];

$salesmen = $this->getSalesmen();
?>

<form id="salesman_price_form" action="<?php echo $this->getUrl('save')?>" method="post"> 
	
<div class="container py-4 pt-5">
	<div class="row">
		<div class="col-md-12 d-flex align-items-center">
			<h1 class="me-auto fs-2">Salesman Price</h1>
			<div class="col-sm-1 me-3" style="width: fit-content;">
				<select class="form-select cursor-pointer" onchange="changeSalesman(this.value)">
					<?php foreach($salesmen->getData() as $salesman):?>
						<?php $selected = $currentSalesman->getId()==$salesman->getId() ? 'selected' : '';?>
					<option <?php echo $selected;?> value="<?php echo $salesman->getId()?>"><?php echo $salesman->fname ." ". $salesman->lname;?></option>
					<?php endforeach?>
				</select>
			</div>
			<a type="button" onclick="ajax.setForm('salesman_price_form').call()" class="btn btn-primary">SAVE PRICES</a>
		</div>
	</div>
</div>

<?php #if($rows){ echo $this->getLayout()->createBlock('core_pager')->setPager($this->getPager())->toHtml();}?>


<div class="responsive">

	<table class="table table-striped">
		<thead>
			<tr class="text-center">
				<th scope="col">Product Id</th>
				<th scope="col">Name</th>
				<th scope="col">SKU</th>
				<th scope="col">COST</th>
				<th scope="col">PRICE</th>
				<th scope="col">QUANTITY</th>
				<th scope="col">SALESMAN PRICE</th>
				<th scope="col">REMOVE</th>
			</tr>
		</thead>
		<tbody class="text-center">
			<?php if (!$rows): ?>
				<tr>
					<td colspan="11">No Records Found</td>
				</tr>
			<?php else:?>
				<?php foreach ($rows->getData() as $row): ?>
				<tr>
					<td>
						<?php echo $row->product_id; ?>
					</td>
					<td>
						<?php echo $row->name; ?>
					</td>
					<td>
						<?php echo $row->sku; ?>
					</td>
					<td>
						<?php echo $row->cost; ?>
					</td>
					<td>
						<?php echo $row->price; ?>
					</td>
					<td>
						<?php echo $row->quantity; ?>
					</td>
					
					<td>
						<input type="text" name="salesman[<?php echo $row->product_id?>]" 
						value="<?php echo $row->salesman_price?>">
					</td>
					<td>
						<?php if($id = $row->entity_id):?>
						<a class="btn btn-success py-1 edit-btn" onclick="ajax.setUrl('<?php echo $this->getUrl('delete',null, ['entity_id'=>$id]);?>').call()">DELETE</a>
						<?php endif?>
					</td>
				</tr>
			<?php endforeach; endif; ?>
		</tbody>
	</table>
</div>

</form>


<script type="text/javascript">
	function changeSalesman(val) {
		ajax.setUrl('<?php echo $this->getUrl('grid',null, null, true)?>' + '&id=' + val).call();
	}
</script>