<?php
$admin = $this->getAdmin();
$action = $admin->admin_id ? 'Edit' : 'Add';
?>

<div class="container">
    <form action="<?php echo $this->getUrl("save",null,["id"=>$admin->admin_id],true)?>" method="post" id="admin-form">
        <div class="row">
            <div class="col-6">
                <h1 class="my-5 mb-4 fs-2">
                    <?php echo $action ?> Admin
                </h1>

                <div class="mb-2 row">
                    <label for="admin-email" class="col-sm-3 col-form-label">Email:</label>
                    <div class="col-sm-5">
                        <input type="email" class="form-control" name="admin[email]" value="<?php echo $admin->email ?>"
                            id="admin-email" placeholder="Enter the email...">
                    </div>
                </div>

                <div class="mb-2 row">
                    <label for="admin-password" class="col-sm-3 col-form-label">Password:</label>
                    <div class="col-sm-5">
                        <input type="password" name="admin[password]" class="form-control"
                            value="<?php echo $admin->password ?>" id="admin-password" placeholder="password...">
                    </div>
                </div>


                <div class="mb-2 row">
                    <label for="admin-status" class="col-sm-3 col-form-label">Status:</label>
                    <div class="col-sm-3">
                        <select class="form-select" name="admin[status]" id="admin-status">
                            <?php foreach ($admin->getResource()->getStatusOptions() as $key => $value): ?>
                                <?php $selected = ($key == $admin->getStatus()) ? 'selected' : ''; ?>
                                <option value="<?php echo $key ?>" <?php echo $selected; ?>>
                                    <?php echo $value ?>
                                </option>
                            <?php endforeach; ?>
                        </select>
                    </div>
                </div>

            </div>

        </div>
        <div class="d-flex mt-5">
            <button onclick ="ajax.setUrl('<?php echo $this->getUrl('grid') ?>').call()" type="button" class="btn btn-danger me-2">Cancel</button>
            <button class="btn btn-primary" type="button" onclick="ajax.setForm('admin-form').call()">Create</button>
        </div>
    </form>
</div>