<!doctype html>
<html lang="en">

<?php $this->getChild('head')->render(); ?>

<body class="vh-100">

    <div class="row">
        <?php $this->getChild('header')->render(); ?>
    </div>

    <div class="container">
        <div class="row">
            <div class="col-12 d-flex justify-content-center position-relative">
                <?php $this->getChild('message')->render(); ?>
            </div>
        </div>
    </div>

    <div class="row mr-0" style="min-height: 34em;">
        <div class="col-1">
            <?php echo $this->getChildHtml('left'); ?>
        </div>
        <div class="col-10">
            <?php echo $this->getChildHtml('content'); ?>
        </div>
        <div class="col-1">
            <?php echo $this->getChildHtml('right'); ?>
        </div>
    </div>

    <div class="row">
         <?php echo $this->getChildHtml('footer'); ?>
        <?php #$this->getChild('footer')->render(); ?>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>

</body>

</html>