<?php
$category = $this->getCategory();
$pathCategories = $this->getPathCategories();
$action = $category->category_id ? 'Edit' : 'Add';
?>

<div class="container">
    <form action="<?php echo $this->getUrl("save",null,["id"=>$category->category_id],true)?>" method="post" id="category-form">
        <div class="row">
            <div class="col-6">
                <h1 class="my-5 mb-4 fs-2">
                    <?php echo $action ?> Category
                </h1>

                <div class="mb-2 row">
                    <label for="category-path" class="col-sm-3 col-form-label">Parent Category:</label>
                    <div class="col-sm-5">
                        <select class="form-select" name="category[parent_id]" id="category-path">
                            <?php foreach ($pathCategories as $key => $value): ?>
                                <?php $selected = ($key == $category->parent_id) ? 'selected' : ''; ?>
                                <option value="<?php echo $key ?>" <?php echo $selected; ?>>
                                    <?php echo $value ?>
                                </option>
                            <?php endforeach; ?>
                        </select>
                    </div>
                </div>

                <div class="mb-2 row">
                    <label for="category-name" class="col-sm-3 col-form-label">Name:</label>
                    <div class="col-sm-5">
                        <input type="text" class="form-control" name="category[name]"
                            value="<?php echo $category->name ?>" id="category-name" placeholder="Category name...">
                    </div>
                </div>



                <div class="mb-2 row">
                    <label for="category-status" class="col-sm-3 col-form-label">Status:</label>
                    <div class="col-sm-3">
                        <select class="form-select" name="category[status]" id="category-status">
                            <?php foreach ($category->getResource()->getStatusOptions() as $key => $value): ?>
                                <?php $selected = ($key == $category->getStatus()) ? 'selected' : ''; ?>
                                <option value="<?php echo $key ?>" <?php echo $selected; ?>>
                                    <?php echo $value ?>
                                </option>
                            <?php endforeach; ?>
                        </select>
                    </div>
                </div>

                <div class="mb-2 row">
                    <label for="category-description" class="col-sm-3 col-form-label">Description:</label>
                    <div class="col-sm-5">
                        <textarea class="form-control" name="category[description]" id="category-description" cols="30"
                            rows="2" placeholder="Description Line..."><?php echo $category->description ?></textarea>
                    </div>
                </div>

            </div>
            <div class="d-flex mt-5">
                <button onclick="ajax.setUrl('<?php echo $this->getUrl('grid') ?>').call()" type="button" class="btn btn-danger me-2">Cancel</button>
                <button class="btn btn-primary" type="button" onclick="ajax.setForm('category-form').call()">Create</button>
            </div>
        </div>
    </form>
</div>