<?php 
$salesman = $this->getSalesman();
$address = $this->getAddress();
$action = $salesman->getId() ? 'Edit' : 'Add';
?>

<div class="container">
    <form action="<?php echo $this->getUrl("save",null,["id"=>$salesman->salesman_id],true)?>" method="post" id="salesman-form">
        <div class="row">
            <div class="col-6">
                <h1 class="my-5 mb-4 fs-2">
                    <?php echo $action ?> Salesman
                </h1>

                <div class="mb-2 row">
                    <label for="attr-fname" class="col-sm-3 col-form-label">First Name:</label>
                    <div class="col-sm-5">
                        <input type="text" class="form-control" name="salesman[fname]"
                            value="<?php echo $salesman->fname ?>" id="attr-fname" placeholder="Enter the first name...">
                    </div>
                </div>

                <div class="mb-2 row">
                    <label for="attr-lname" class="col-sm-3 col-form-label">Last Name:</label>
                    <div class="col-sm-5">
                        <input type="text" class="form-control" name="salesman[lname]"
                            value="<?php echo $salesman->lname ?>" id="attr-lname" placeholder="Last name...">
                    </div>
                </div>

                <div class="mb-2 row">
                    <label for="attr-email" class="col-sm-3 col-form-label">Email:</label>
                    <div class="col-sm-5">
                        <input type="email" required class="form-control" name="salesman[email]"
                            value="<?php echo $salesman->email ?>" id="attr-email" placeholder="Email...">
                    </div>
                </div>

                <div class="mb-2 row">
                    <label for="attr-mobile" class="col-sm-3 col-form-label">Mobile Number:</label>
                    <div class="col-sm-5">
                        <input type="number" required class="form-control" name="salesman[mobile]"
                            value="<?php echo $salesman->mobile ?>" id="attr-mobile" placeholder="Mobile number...">
                    </div>
                </div>


                <div class="mb-2 row">
                    <label for="attr-gender" class="col-sm-3 col-form-label">Gender:</label>
                    <div class="col-sm-3">
                        <select class="form-select cursor-pointer" name="salesman[gender]" id="attr-gender">
                            <?php foreach ($salesman->getResource()->getGenderOptions() as $key => $value): ?>
                                <?php $selected = ($salesman->getGender() == $key) ? 'selected' : ''; ?>
                                <option value="<?php echo $key ?>" <?php echo $selected; ?>>
                                    <?php echo $value; ?>
                                </option>
                            <?php endforeach; ?>
                        </select>
                    </div>
                </div>

                <div class="mb-2 row">
                    <label for="attr-status" class="col-sm-3 col-form-label">Status:</label>
                    <div class="col-sm-3">
                        <select class="form-select" name="salesman[status]" id="attr-status">
                            <?php foreach ($salesman->getResource()->getStatusOptions() as $key => $value): ?>
                                <?php $selected = ($key == $salesman->getStatus()) ? 'selected' : ''; ?>
                                <option value="<?php echo $key ?>" <?php echo $selected; ?>>
                                    <?php echo $value ?>
                                </option>
                            <?php endforeach; ?>
                        </select>
                    </div>
                </div>

                <div class="mb-2 row">
                    <label for="attr-company" class="col-sm-3 col-form-label">Company:</label>
                    <div class="col-sm-5">
                        <input type="text" class="form-control" name="salesman[company]"
                            value="<?php echo $salesman->company ?>" id="attr-company" placeholder="Company name...">
                    </div>
                </div>

            </div>

            <div class="col-6">
                <div class="container">
                    <h1 class="my-5 mb-4 fs-2">Address</h1>
                    <div class="mb-2 row">
                        <label for="attr-address" class="col-sm-3 col-form-label">Address:</label>
                        <div class="col-sm-5">
                            <textarea class="form-control" name="address[address]" id="attr-address" cols="30" rows="2"
                                placeholder="Address Line..."><?php echo $address->address ?></textarea>
                        </div>
                    </div>


                    <div class="mb-2 row">
                        <label for="attr-city" class="col-sm-3 col-form-label">City:</label>
                        <div class="col-sm-5">
                            <input type="text" class="form-control" name="address[city]"
                                value="<?php echo $address->city ?>" id="attr-city" placeholder="City...">
                        </div>
                    </div>

                    <div class="mb-2 row">
                        <label for="attr-zipcode" class="col-sm-3 col-form-label">Zipcode:</label>
                        <div class="col-sm-5">
                            <input type="number" required class="form-control" name="address[zipcode]"
                                value="<?php echo $address->zipcode ?>" id="attr-zipcode" placeholder="Zipcode...">
                        </div>
                    </div>

                    <div class="mb-2 row">
                        <label for="attr-state" class="col-sm-3 col-form-label">State:</label>
                        <div class="col-sm-5">
                            <input type="text" class="form-control" name="address[state]"
                                value="<?php echo $address->state ?>" id="attr-state" placeholder="State...">
                        </div>
                    </div>

                    <div class="mb-2 row">
                        <label for="attr-country" required class="col-sm-3 col-form-label">Country:</label>
                        <div class="col-sm-5">
                            <input type="text" class="form-control" name="address[country]"
                                value="<?php echo $address->country ?>" id="attr-country" placeholder="Country...">
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="d-flex  mt-5">
            <button onclick="ajax.setUrl('<?php echo $this->getUrl('grid') ?>').call()" type="button" class="btn btn-danger me-2">Cancel</button>
            <button class="btn btn-primary" type="button" onclick="ajax.setForm('salesman-form').call()">Create</button>
        </div>
    </form>
</div>
